_extends: .github
# https://github.com/apps/settings
# https://github.com/repository-settings/app

repository:
  #name: NewRepo
  description: Scripts for the general public
  topics: scripts, public, useful, proxmox, docker, bash, batch, powershell, python

  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true
  has_projects: false

  default_branch: master

  allow_squash_merge: true
  allow_rebase_merge: true
  allow_merge_commit: false
  
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true